# Site settings
title: Alces Flight
email: github@alces-flight.com
description: >
  Alces Software Products
baseurl: ""
url: "http://alces-flight.github.io/"
twitter_username: alces-software
github_username: alces-software

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
